#example toml configuration (for now)

#NOTE: Look how to add dynamic library support

#---------------
#PROJECT SETTINGS
#---------------
[project]
name = "autoc" #project name
language = "c++"
#type options:
#"c++" admits compiling c and cpp with its own compiler, then links with cxx comp
#"c" only uses cc compiler
toolchain = "gnu"
target = "app"

source_directory = "src"
include_directory = "include"
lib_directory = "lib"

[project.extensions]
".c" = "cc"
".cpp" = "cxx"


#---------------
#TOOLCHAINS
#---------------
[toolchain.gnu]
cc = "gcc"  #c compiler
cxx = "g++" #cpp compiler

[toolchain.other]
cc = "othercc"
cxx = "other++"

#---------------
#MODES
#---------------
[modes.release]
#general flags of the mode, added on top of target flags
compile_flags = ["-O3", "-pedantic"]
link_flags = ["-O3", "-pedantic"]
defines = ["NDEBUG"]

[modes.debug]
compile_flags = ["-g", "-pedantic"]
link_flags = ["-g", "-pedantic"]
defines = ["DEBUG"]

#------------
#TARGETS
#------------


#each target must have its own directory inside the src folder.
#each target directory must be independent from other targets.
#the target directoy name must be the same as the target name example: [target.app] -> src/app/

[targets.app]
type = "executable" #output type: executable, static_lib
output = "app_name" #name of the output

compile_flags = []  #compile time flags
link_flags = []     #linkage time flags

static_libraries = [] #static libraries to be added when linking

#other targets in which it depends, they cant be executables, as executables cant be linked together
dependencies = ["dep1"]

[targets.dep1]
type = "static_lib"
output = "dep1"

compile_flags = []
link_flags = []

static_libraries = [] 

dependencies = []

#-------------
#Build tool config
#-------------
[autoc]
obj_directory = "obj"           #.o
dependencies_directory = "deps" #.d
build_directory = "build"

#Not implemented, will serve for parallel compilation/linking
jobs = 1
