compiler = g++


src_directory = src
obj_directory = obj
include_directory = include
build_directory = build

src_extension = .cpp

compile_flags = -Wall -Werror -pedantic-errors
build_flags = 

exec_name = autoc

static_libraries = 
